server:
  port: 28852
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

  datasource:
    url: "jdbc:h2:file:../service_db"
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        trace: false
        web-allow-others: false

login:
  max-failed-attempts: 5
  breached-passwords-file: breached-passwords.txt