server:
  port: 28852

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true