server:
  port: 28852
  error:
    include-message: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
